### ISSUE TITLE
Country data is missing after install

### ISSUE THREAD

**Issue by colllin** [OpenBookPrices/country-data#50] opened 2016-04-01 16:52 UTC
Have you ever seen this?  I `npm install --save country-data` then `var countries = require('country-data').countries;`, and `countries.all` looks like `{}`.

**Comment by evdb** [comment] 2016-06-16 11:25
I've not seen that. If you can reproduce please let me know the various versions of node, this module etc.

The following works for me:

``` shell
$ npm install --save country-data
country-data@0.0.24 node_modules/country-data
├── currency-symbol-map@2.2.0
└── underscore@1.8.3

$ echo "var countries = require('country-data').countries; console.log( countries.all );" | node | head
[ { alpha2: 'AC',
    alpha3: '',
    countryCallingCodes: [ '+247' ],
    currencies: [ 'USD' ],
    ioc: 'SHP',
    languages: [ 'eng' ],
    name: 'Ascension Island',
    status: 'reserved' },
  { alpha2: 'AD',
    alpha3: 'AND',
$
```

Closing, but please re-open if needed.

**Closed by evdb** 2016-06-16 11:25 UTC
